version: "3.6"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springAPI
      MYSQL_ROOT_PASSWORD: Anshul@6262
  
  dockerapi:
    build:
      context: .
    container_name: dockerapi_container
    depends_on:
      - mysql
    ports:
      - "8080:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springAPI
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Anshul@6262
      SPRING_APPLICATION_NAME: DockerAPI
      SERVER_PORT: 8082
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    