version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springapi
      MYSQL_ROOT_PASSWORD: Anshul@6262

  dockerapi:
    build: 
      context: .
    expose:
      - "8082"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_NAME: DockerAPI
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Anshul@6262
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dockerapi
    
    
    
    
